language: cpp
compiler: gcc
os: linux

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-4.8
           - g++-4.8
    
before_install:
  - cd ..
  - git clone https://github.com/redis/hiredis.git
  - cd hiredis
  - make
  - sudo make install
  - cd ..
  
  - git clone https://github.com/sewenew/redis-plus-plus.git
  - cd redis-plus-plus  
  - mkdir compile  
  - cd compile  
  - cmake -DCMAKE_BUILD_TYPE=Release ..  
  - make  
  - sudo make install  

  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq update

install:
  - sudo apt-get --yes install qt55base qt55imageformats qt55svg

before_script:
  # Qt variables
  - QTDIR="/opt/qt55"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt55/bin/qt55-env.sh

script:
    ############################################################################
    # Build main and tests
    ############################################################################
    - cd ../../edu-DirMonitor
    - cd test
    - mkdir build && cd build
    - cmake ..
    - cmake --build . 
    - ./edu-DirMonitor-Test

    - cd ../..
    - mkdir build && cd build
    - cmake .. 
    - cmake --build .
